{
    id: '47061744',
    username: 'jaredmpeterson',
    displayName: 'jared',
    photos: [{
        value: 'https://pbs.twimg.com/profile_images/3704795208/3fd28709f1a8543b101df9ac57da40f6_normal.jpeg'
    }],
    provider: 'twitter',
    _raw: '{"id":47061744,"id_str":"47061744","name":"jared","screen_name":"jaredmpeterson","location":"79 Inches Above Ground Level","description":"Based on actual events. Only the people, places and events have been changed.","url":null,"entities":{"description":{"urls":[]}},"protected":false,"followers_count":191,"friends_count":291,"listed_count":8,"created_at":"Sun Jun 14 08:53:11 +0000 2009","favourites_count":2235,"utc_offset":-21600,"time_zone":"Mountain Time (US & Canada)","geo_enabled":true,"verified":false,"statuses_count":4786,"lang":"en","status":{"created_at":"Mon Jun 06 21:12:15 +0000 2016","id":739927908299485184,"id_str":"739927908299485184","text":"Game Over: I win at #faceswap! @quaker I just found your new spokes\\u2026 https:\\/\\/t.co\\/n93lONcsd8","truncated":false,"entities":{"hashtags":[{"text":"faceswap","indices":[20,29]}],"symbols":[],"user_mentions":[{"screen_name":"Quaker","name":"QuakerOats","id":18940252,"id_str":"18940252","indices":[31,38]}],"urls":[{"url":"https:\\/\\/t.co\\/n93lONcsd8","expanded_url":"https:\\/\\/www.instagram.com\\/p\\/BGU-HpxIP0YulAlRPnwN3qkdJYT125u-zDyZBc0\\/","display_url":"instagram.com\\/p\\/BGU-HpxIP0Yu\\u2026","indices":[69,92]}]},"source":"\\u003ca href=\\"http:\\/\\/instagram.com\\" rel=\\"nofollow\\"\\u003eInstagram\\u003c\\/a\\u003e","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":2,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"en"},"contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"FFFFFF","profile_background_image_url":"http:\\/\\/pbs.twimg.com\\/profile_background_images\\/27779119\\/Clint_Eastwood_by_MrMonday.png","profile_background_image_url_https":"https:\\/\\/pbs.twimg.com\\/profile_background_images\\/27779119\\/Clint_Eastwood_by_MrMonday.png","profile_background_tile":false,"profile_image_url":"http:\\/\\/pbs.twimg.com\\/profile_images\\/3704795208\\/3fd28709f1a8543b101df9ac57da40f6_normal.jpeg","profile_image_url_https":"https:\\/\\/pbs.twimg.com\\/profile_images\\/3704795208\\/3fd28709f1a8543b101df9ac57da40f6_normal.jpeg","profile_banner_url":"https:\\/\\/pbs.twimg.com\\/profile_banners\\/47061744\\/1351543239","profile_link_color":"0084B4","profile_sidebar_border_color":"FFFFFF","profile_sidebar_fill_color":"DDFFCC","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":false,"default_profile":false,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false}',
    _json: {
        id: 47061744,
        id_str: '47061744',
        name: 'jared',
        screen_name: 'jaredmpeterson',
        location: '79 Inches Above Ground Level',
        description: 'Based on actual events. Only the people, places and events have been changed.',
        url: null,
        entities: {
            description: [Object]
        },
        protected: false,
        followers_count: 191,
        friends_count: 291,
        listed_count: 8,
        created_at: 'Sun Jun 14 08:53:11 +0000 2009',
        favourites_count: 2235,
        utc_offset: -21600,
        time_zone: 'Mountain Time (US & Canada)',
        geo_enabled: true,
        verified: false,
        statuses_count: 4786,
        lang: 'en',
        status: {
            created_at: 'Mon Jun 06 21:12:15 +0000 2016',
            id: 739927908299485200,
            id_str: '739927908299485184',
            text: 'Game Over: I win at #faceswap! @quaker I just found your new spokes… https://t.co/n93lONcsd8',
            truncated: false,
            entities: [Object],
            source: '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 2,
            favorited: false,
            retweeted: false,
            possibly_sensitive: false,
            lang: 'en'
        },
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'FFFFFF',
        profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/27779119/Clint_Eastwood_by_MrMonday.png',
        profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/27779119/Clint_Eastwood_by_MrMonday.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/3704795208/3fd28709f1a8543b101df9ac57da40f6_normal.jpeg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/3704795208/3fd28709f1a8543b101df9ac57da40f6_normal.jpeg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/47061744/1351543239',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: 'FFFFFF',
        profile_sidebar_fill_color: 'DDFFCC',
        profile_text_color: '333333',
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false
    },
    _accessLevel: 'read'
}
